// "Your site" bootstrap — the multi-region layer over the legacy UI.
//
// Default behavior is untouched: with no site chosen, script.js renders the
// legacy Carrboro dataset from data.js exactly as before. Choosing a site
// builds a SiteContext from the bundled providers, resolves the calendar
// through the engine (curated Piedmont pack where it applies, computed
// estimates elsewhere), adapts the result to the legacy plant shape, and hands
// it to script.js via window.__applyPlantData.
//
// app/lib/** and app/data/** are committed artifacts generated by
// scripts/build-app-lib.mjs (CI enforces freshness) — no deploy-time build.

import { resolveAll } from "./lib/engine/resolve.js";
import { CROP_CATALOG } from "./lib/crop-catalog.js";
import {
  buildSiteContext,
  createStaticFrostProvider,
  createStaticZoneProvider,
  haversineKm,
} from "./lib/providers/static.js";

const STORAGE_KEY = "pp:site:v1";
const MONTH_LEN = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
const MONTH_ABBR = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const els = {
  panel: document.getElementById("sitePanel"),
  summary: document.getElementById("siteSummary"),
  stats: document.getElementById("siteStats"),
  note: document.getElementById("siteNote"),
  quickPick: document.getElementById("siteQuickPick"),
  geoBtn: document.getElementById("siteGeoBtn"),
  lat: document.getElementById("siteLat"),
  lng: document.getElementById("siteLng"),
  applyBtn: document.getElementById("siteApplyBtn"),
  resetBtn: document.getElementById("siteResetBtn"),
  error: document.getElementById("siteError"),
};

let bundles = null; // { frostTable, zonePoints, pack, providers }

async function loadBundles() {
  if (bundles) return bundles;
  const [frostTable, zonePoints, pack] = await Promise.all(
    ["frost-stations.json", "zone-points.json", "piedmont-pack.json"].map((f) =>
      fetch(new URL(`./data/${f}`, import.meta.url)).then((r) => {
        if (!r.ok) throw new Error(`failed to load ${f}: ${r.status}`);
        return r.json();
      })
    )
  );
  bundles = {
    frostTable,
    zonePoints,
    pack,
    providers: {
      frost: createStaticFrostProvider(frostTable),
      zone: createStaticZoneProvider(zonePoints),
    },
  };
  return bundles;
}

function fmtDay(doy) {
  let d = ((Math.round(doy) - 1) % 365 + 365) % 365 + 1;
  for (let m = 0; m < 12; m++) {
    if (d <= MONTH_LEN[m]) return `${MONTH_ABBR[m]} ${d}`;
    d -= MONTH_LEN[m];
  }
  return "?";
}

function fmtDth(dth) {
  if (!dth) return "";
  const parts = [];
  if (dth.transplant) parts.push(`T = ${dth.transplant[0]}-${dth.transplant[1]}`);
  if (dth.direct) parts.push(`S = ${dth.direct[0]}-${dth.direct[1]}`);
  return parts.join(", ");
}

// Resolver output → the legacy plant shape script.js renders. Curated rows
// keep pack order (and their legacy names, so the detail panel's name-keyed
// review data still works); computed rows follow, alphabetical, flagged.
function adaptCalendars(calendars, pack) {
  const packOrder = new Map(pack.crops.map((c, i) => [c.crop, i]));
  const rows = [...calendars].sort((a, b) => {
    const ai = packOrder.has(a.crop) ? packOrder.get(a.crop) : Infinity;
    const bi = packOrder.has(b.crop) ? packOrder.get(b.crop) : Infinity;
    if (ai !== bi) return ai - bi;
    const an = CROP_CATALOG[a.crop]?.displayName ?? a.crop;
    const bn = CROP_CATALOG[b.crop]?.displayName ?? b.crop;
    return an.localeCompare(bn);
  });
  return rows.map((cal, i) => {
    const entry = CROP_CATALOG[cal.crop];
    return {
      id: i + 1,
      name: entry?.displayName ?? cal.crop,
      type: entry?.category === "flower" ? "flower" : "vegetable",
      spacing: entry?.spacingIn ?? "",
      daysToHarvest: fmtDth(entry?.daysToMaturity),
      months: cal.grid,
      computedEstimate: cal.origin === "computed",
    };
  });
}

function showError(msg) {
  if (els.error) {
    els.error.textContent = msg || "";
    els.error.hidden = !msg;
  }
}

async function applySite(site) {
  const { pack, providers } = await loadBundles();
  const ctx = await buildSiteContext(site.lat, site.lng, providers);
  const calendars = resolveAll(ctx, { catalog: CROP_CATALOG, packs: [pack] });
  if (!calendars.length) throw new Error("no crops resolvable for this location");

  const curated = calendars.filter((c) => c.origin === "curated").length;
  const computed = calendars.length - curated;
  const inPackFootprint = curated > 0;

  const plants = adaptCalendars(calendars, pack);
  window.__applyPlantData?.(plants, inPackFootprint ? pack.regional?.tasks ?? null : null);

  // Panel: the honest numbers behind the calendar.
  const last = ctx.frost.lastFrost["32/50"];
  const first = ctx.frost.firstFrost["32/50"];
  if (els.summary) {
    els.summary.textContent = `${site.label ?? `${site.lat.toFixed(2)}, ${site.lng.toFixed(2)}`} — zone ${ctx.zone}`;
  }
  if (els.stats) {
    els.stats.innerHTML = "";
    const items = [
      ["Last frost (50%)", fmtDay(last)],
      ["First frost (50%)", fmtDay(first)],
      ["Frost-free days", String(ctx.frostFreeDays)],
      ["Frost data", `${ctx.frost.station.id} · ${Math.round(ctx.frost.station.distanceKm)} km away (NCEI ${ctx.datasetVersions.ncei ?? "1991-2020"})`],
      ["Calendar", computed === 0 ? `${curated} crops, hand-reviewed` : `${curated} hand-reviewed · ${computed} computed estimates`],
    ];
    for (const [k, v] of items) {
      const li = document.createElement("li");
      const b = document.createElement("strong");
      b.textContent = `${k}: `;
      li.append(b, v);
      els.stats.appendChild(li);
    }
    els.stats.hidden = false;
  }
  if (els.note) {
    if (inPackFootprint) {
      const ref = pack.referencePoint;
      const km = ref ? Math.round(haversineKm(site.lat, site.lng, ref.lat, ref.lng)) : null;
      els.note.textContent =
        km !== null && km > 5
          ? `Hand-reviewed timing validated at ${ref.label ?? "the reference garden"}, ~${km} km from this site — local frost dates may differ by a week or more.`
          : `Hand-reviewed timing validated here (${ref?.label ?? "reference garden"}).`;
    } else {
      els.note.textContent =
        "No hand-reviewed data covers this area yet — all timing shown is a computed estimate from frost normals and generic crop rules. Treat it as a starting point, not a reviewed calendar.";
    }
    els.note.hidden = false;
  }
  showError("");
}

function currentSite() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

function setSite(site) {
  try {
    if (site) localStorage.setItem(STORAGE_KEY, JSON.stringify(site));
    else localStorage.removeItem(STORAGE_KEY);
  } catch {
    /* private mode — session-only is fine */
  }
}

function resetToDefault() {
  setSite(null);
  window.__applyPlantData?.(null);
  if (els.summary) els.summary.textContent = "Carrboro, NC (default) — zone 8a";
  if (els.stats) els.stats.hidden = true;
  if (els.note) {
    els.note.textContent =
      "Showing the original hand-reviewed Carrboro/Piedmont calendar. Pick a location to preview your own site.";
    els.note.hidden = false;
  }
  showError("");
}

async function chooseSite(lat, lng, label) {
  if (!(lat >= 17 && lat <= 72 && lng >= -180 && lng <= -60)) {
    showError("This planner uses US data sources (NOAA/USDA) — that point looks outside their coverage.");
    return;
  }
  const site = { lat, lng, ...(label ? { label } : {}) };
  try {
    await applySite(site);
    setSite(site);
  } catch (err) {
    showError(`Could not build a calendar for that location: ${err.message}`);
  }
}

async function initPanel() {
  if (!els.panel) return;

  // Quick picks from the bundled station seed (real NCEI stations).
  try {
    const { frostTable } = await loadBundles();
    if (els.quickPick) {
      for (const s of frostTable.stations) {
        const opt = document.createElement("option");
        opt.value = `${s.lat},${s.lng}`;
        opt.textContent = s.name.replace(/, [A-Z]{2} US$/, (m) => m.replace(" US", ""));
        els.quickPick.appendChild(opt);
      }
    }
  } catch (err) {
    showError(`Site data failed to load: ${err.message}`);
    return;
  }

  els.quickPick?.addEventListener("change", () => {
    const v = els.quickPick.value;
    if (!v) return;
    const [lat, lng] = v.split(",").map(Number);
    const label = els.quickPick.selectedOptions[0]?.textContent ?? undefined;
    chooseSite(lat, lng, label);
  });

  els.geoBtn?.addEventListener("click", () => {
    if (!navigator.geolocation) {
      showError("Geolocation is not available in this browser.");
      return;
    }
    els.geoBtn.disabled = true;
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        els.geoBtn.disabled = false;
        chooseSite(pos.coords.latitude, pos.coords.longitude, "My location");
      },
      () => {
        els.geoBtn.disabled = false;
        showError("Location permission denied — pick a nearby city or enter coordinates instead.");
      },
      { maximumAge: 600000, timeout: 10000 }
    );
  });

  els.applyBtn?.addEventListener("click", () => {
    const lat = Number(els.lat?.value);
    const lng = Number(els.lng?.value);
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
      showError("Enter both latitude and longitude as numbers (e.g. 35.91, -79.08).");
      return;
    }
    chooseSite(lat, lng);
  });

  els.resetBtn?.addEventListener("click", resetToDefault);

  const saved = currentSite();
  if (saved && Number.isFinite(saved.lat) && Number.isFinite(saved.lng)) {
    applySite(saved).catch((err) => {
      showError(`Saved location failed to load (${err.message}) — showing the Carrboro default.`);
      resetToDefault();
    });
  } else {
    resetToDefault();
  }
}

initPanel();
